version: "3.8"

services:
  db:
    image: postgres:16-alpine
    # restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: cnc-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80" # Adjust port as needed
    volumes:
      - ./app:/app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000" # Adjust port as needed
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:newpassword@db:5432/cnc-db
      PORT: 3000
      FRONTEND_URL: http://localhost
      NODE_ENV: development
      SECRET_KEY: "secret-key"

volumes:
  db:
