name: Contract CI/CD

on:
    pull_request:
        branches:
        - master
        - develop
        paths:
        - 'contract/**'
    workflow_dispatch:
jobs:
    contract_ci_cd:
        runs-on: ubuntu-latest
        steps:
            - name: 🛫 Checkout code
              uses: actions/checkout@v2

            - name: 🏗 Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 18.14.0
                cache: 'npm'

            - name: ⚙️ NPM install
              run: npm install
              working-directory: ./contract

            - name: ⚒️ Run Compile
              run: npm run compile
              working-directory: ./contract

            - name: ⚒️ Create Typechain
              run: npm run typechain
              working-directory: ./contract

            - name: 🧪 Run Test
              run: npm run test
              working-directory: ./contract
            
            - name: 🚀 Tips Deployment
              run: npm run deploy:tips
              working-directory: ./contract
