name: Vitest Unit Tests

on:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Set up NodeJS 20.10.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: "npm"
          cache-dependency-path: ./app/package-lock.json

      - name: 💻 Run Vitest
        run: |
          npm ci
          npm run test:unit:coverage

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: unittests
